# Generated by Django 2.1.7 on 2019-04-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=models.CharField(max_length=20, verbose_name='商品详情'),
        ),
    ]
